### ISSUE TITLE
[IOS] - Send Screen - ZEC with . -> USD with NaN

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zecwallet-mobile-gunfork#15]
@zancas 
If you fill the ZEC field with '.' appear 'Invalid Amount!', That's good, but at the same time USD have NaN. This is so ugly.
Same problem if tyou put a '.' in USD field... ZEC have NaN.

![IMG_0017](https://user-images.githubusercontent.com/43755989/167955989-18496e90-f06f-4325-93bc-08aec5337a2c.PNG)

**Comment by zancas** [comment]
I agree we need to fix this.   Nice find!

**Comment by juanky201271** [comment]
Another issue detected... It's nothing but it bothers me...

In this screen yo can see all of numbers with ',' (es config) but the price of Zec in $ have '.' (us config). I'm going to fix that too.

![IMG_6367](https://user-images.githubusercontent.com/43755989/168120695-7dd15e09-8892-4f46-8701-58bea206ba73.PNG)

**Comment by juanky201271** [comment]
The same problem in Server Info screen (my device have ES config decimal point (,) and here is always '.':

![IMG_6371](https://user-images.githubusercontent.com/43755989/168128588-8b98ba1c-43ae-4df5-be61-675fb268ca13.PNG)

**Comment by zancas** [comment]
Nice find!   I think this is a high-priority bugfix!

**Comment by juanky201271** [comment]
For this, I'm going to create a new PR-branch here and cherry-pick this two commits because this fixed it's important. Let me know if you think something different.

**Comment by zancas** [comment]
That sounds fine.

**Comment by juanky201271** [comment]
I'm sorry about the mess with many commits, the PR is correct with the last and valid commit.

**Comment by zancas** [comment]
This should have been fixed when #19 merged.
